// <auto-generated />
using System;
using AccountInfo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountInfo.Data.Migrations
{
    [DbContext(typeof(AppInfoDbContext))]
    [Migration("20260205225407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountInfo.Data.Models.AccountManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AMCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AMEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AMName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AMPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int?>("InternetAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("PhoneAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AMEmail");

                    b.HasIndex("AccountType");

                    b.HasIndex("InternetAccountId");

                    b.HasIndex("PhoneAccountId");

                    b.ToTable("AccountManagers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountManager_ValidAccountType", "(AccountType = 2 AND PhoneAccountId IS NOT NULL AND InternetAccountId IS NULL) OR \r\n                      (AccountType = 1 AND InternetAccountId IS NOT NULL AND PhoneAccountId IS NULL) OR \r\n                      (AccountType = 3 AND InternetAccountId IS NOT NULL AND PhoneAccountId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.InternetAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountAddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AdminAnswers")
                        .HasColumnType("text");

                    b.Property<string>("AdminInfo")
                        .HasColumnType("text");

                    b.Property<string>("AdminPassword")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdminPortalURL")
                        .HasColumnType("text");

                    b.Property<string>("AdminUsername")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("BillEntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CircuitId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConnectionSpeed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConnectionType")
                        .HasColumnType("text");

                    b.Property<string>("DNSPrimary")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DNSSecondary")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DataAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultGateway")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InternetProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubnetMask")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("InternetProvider");

                    b.HasIndex("LocationId");

                    b.ToTable("InternetAccounts", (string)null);
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AreaManager")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("Email");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Hours")
                        .HasColumnType("text");

                    b.Property<string>("LocName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocNum")
                        .HasColumnType("integer");

                    b.Property<int>("LoctypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("RecordAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("StoreManager")
                        .HasColumnType("text");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("LocNum")
                        .IsUnique();

                    b.HasIndex("LoctypeId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Loctype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoctypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Loctypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoctypeName = "Corporate"
                        },
                        new
                        {
                            Id = 2,
                            LoctypeName = "Metal Mart"
                        },
                        new
                        {
                            Id = 3,
                            LoctypeName = "Service Center"
                        },
                        new
                        {
                            Id = 4,
                            LoctypeName = "Plant"
                        },
                        new
                        {
                            Id = 5,
                            LoctypeName = "Other"
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.PhoneAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountAddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BillEntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LocalAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LocalProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("LongDistanceAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LongDistanceProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RolloverNumbers")
                        .HasColumnType("text");

                    b.Property<string>("TermNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TollFreeNumber1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TollFreeNumber2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("LocalProvider");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("PhoneAccounts", (string)null);
                });

            modelBuilder.Entity("AccountInfo.Data.Models.RepairContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int?>("InternetAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("PhoneAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("RPCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RPName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RPPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RPPortal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountType");

                    b.HasIndex("InternetAccountId");

                    b.HasIndex("PhoneAccountId");

                    b.ToTable("RepairContacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_RepairContact_ValidAccountType", "(AccountType = 2 AND PhoneAccountId IS NOT NULL AND InternetAccountId IS NULL) OR \r\n                      (AccountType = 1 AND InternetAccountId IS NOT NULL AND PhoneAccountId IS NULL) OR \r\n                      (AccountType = 3 AND InternetAccountId IS NOT NULL AND PhoneAccountId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.AccountManager", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.InternetAccount", "InternetAccount")
                        .WithMany("AccountManagers")
                        .HasForeignKey("InternetAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountInfo.Data.Models.PhoneAccount", "PhoneAccount")
                        .WithMany("AccountManagers")
                        .HasForeignKey("PhoneAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InternetAccount");

                    b.Navigation("PhoneAccount");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.InternetAccount", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.Location", "Location")
                        .WithMany("InternetAccounts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Location", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.Loctype", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LoctypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.PhoneAccount", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.Location", "Location")
                        .WithOne("PhoneAccount")
                        .HasForeignKey("AccountInfo.Data.Models.PhoneAccount", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.RepairContact", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.InternetAccount", "InternetAccount")
                        .WithMany("RepairContacts")
                        .HasForeignKey("InternetAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountInfo.Data.Models.PhoneAccount", "PhoneAccount")
                        .WithMany("RepairContacts")
                        .HasForeignKey("PhoneAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InternetAccount");

                    b.Navigation("PhoneAccount");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.InternetAccount", b =>
                {
                    b.Navigation("AccountManagers");

                    b.Navigation("RepairContacts");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Location", b =>
                {
                    b.Navigation("InternetAccounts");

                    b.Navigation("PhoneAccount");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Loctype", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.PhoneAccount", b =>
                {
                    b.Navigation("AccountManagers");

                    b.Navigation("RepairContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
