// <auto-generated />
using System;
using AccountInfo.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountInfo.Data.Migrations
{
    [DbContext(typeof(AppInfoDbContext))]
    [Migration("20260210170652_AddDescriptionToLocation")]
    partial class AddDescriptionToLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountInfo.Data.Models.AccountManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AMCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AMEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AMName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AMPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int?>("InternetAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("PhoneAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AMEmail");

                    b.HasIndex("AccountType");

                    b.HasIndex("InternetAccountId");

                    b.HasIndex("PhoneAccountId");

                    b.ToTable("AccountManagers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountManager_ValidAccountType", "(\"AccountType\" = 2 AND \"PhoneAccountId\" IS NOT NULL AND \"InternetAccountId\" IS NULL) OR \r\n                     (\"AccountType\" = 1 AND \"InternetAccountId\" IS NOT NULL AND \"PhoneAccountId\" IS NULL) OR \r\n                     (\"AccountType\" = 3 AND \"InternetAccountId\" IS NOT NULL AND \"PhoneAccountId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AMCompany = "AT&T Business Support",
                            AMEmail = "j.martinez@att.com",
                            AMName = "Jennifer Martinez",
                            AMPhone = "888-321-8880",
                            AccountType = 1,
                            InternetAccountId = 1
                        },
                        new
                        {
                            Id = 2,
                            AMCompany = "Comcast Business Sales",
                            AMEmail = "m.thompson@comcast.com",
                            AMName = "Michael Thompson",
                            AMPhone = "800-555-2020",
                            AccountType = 1,
                            InternetAccountId = 2
                        },
                        new
                        {
                            Id = 3,
                            AMCompany = "AT&T Business Voice",
                            AMEmail = "p.rodriguez@att.com",
                            AMName = "Patricia Rodriguez",
                            AMPhone = "888-321-8881",
                            AccountType = 2,
                            PhoneAccountId = 1
                        },
                        new
                        {
                            Id = 4,
                            AMCompany = "CenturyLink Business",
                            AMEmail = "r.chen@centurylink.com",
                            AMName = "Robert Chen",
                            AMPhone = "877-453-1234",
                            AccountType = 2,
                            PhoneAccountId = 2
                        },
                        new
                        {
                            Id = 5,
                            AMCompany = "Suddenlink/AT&T Business",
                            AMEmail = "a.johnson@business.com",
                            AMName = "Amanda Johnson",
                            AMPhone = "866-789-4560",
                            AccountType = 3,
                            InternetAccountId = 3,
                            PhoneAccountId = 3
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.InternetAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountAddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AdminAnswers")
                        .HasColumnType("text");

                    b.Property<string>("AdminInfo")
                        .HasColumnType("text");

                    b.Property<string>("AdminPassword")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdminPortalURL")
                        .HasColumnType("text");

                    b.Property<string>("AdminUsername")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("BillEntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CircuitId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConnectionSpeed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConnectionType")
                        .HasColumnType("text");

                    b.Property<string>("DNSPrimary")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DNSSecondary")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DataAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultGateway")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InternetProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubnetMask")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("InternetProvider");

                    b.HasIndex("LocationId");

                    b.ToTable("InternetAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountAddedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            AdminInfo = "Primary internet connection for HQ",
                            AdminPassword = "SecurePass123!",
                            AdminPortalURL = "https://business.att.com",
                            AdminUsername = "hq_admin",
                            BillEntryDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CircuitId = "ATTF/123456/DFW",
                            ConnectionSpeed = "1 Gbps",
                            ConnectionType = "Fiber",
                            DNSPrimary = "8.8.8.8",
                            DNSSecondary = "8.8.4.4",
                            DataAccountNumber = "ATT-FB-1234567",
                            DefaultGateway = "203.0.113.1",
                            IPAddress = "203.0.113.10",
                            InternetProvider = "AT&T Business Fiber",
                            LocationId = 1,
                            MonthlyCost = 599.99m,
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceType = "Dedicated Fiber",
                            SubnetMask = "255.255.255.0"
                        },
                        new
                        {
                            Id = 2,
                            AccountAddedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            AdminPortalURL = "https://business.comcast.com",
                            AdminUsername = "metalmart_admin",
                            BillEntryDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ConnectionSpeed = "500 Mbps",
                            ConnectionType = "Cable",
                            DNSPrimary = "75.75.75.75",
                            DNSSecondary = "75.75.76.76",
                            DataAccountNumber = "CMCST-987654321",
                            DefaultGateway = "198.51.100.1",
                            IPAddress = "198.51.100.25",
                            InternetProvider = "Comcast Business",
                            LocationId = 2,
                            MonthlyCost = 299.99m,
                            Notes = "Backup connection also available",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceType = "Cable",
                            SubnetMask = "255.255.255.0"
                        },
                        new
                        {
                            Id = 3,
                            AccountAddedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            BillEntryDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ConnectionSpeed = "300 Mbps",
                            ConnectionType = "Cable",
                            DNSPrimary = "8.8.8.8",
                            DataAccountNumber = "SDLN-456789123",
                            DefaultGateway = "192.0.2.1",
                            IPAddress = "192.0.2.50",
                            InternetProvider = "Suddenlink Business",
                            LocationId = 3,
                            MonthlyCost = 199.99m,
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceType = "Cable",
                            SubnetMask = "255.255.255.0"
                        },
                        new
                        {
                            Id = 4,
                            AccountAddedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            AdminPortalURL = "https://business.att.com",
                            AdminUsername = "plant_admin",
                            BillEntryDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CircuitId = "ATTF/987654/DFW",
                            ConnectionSpeed = "500 Mbps",
                            ConnectionType = "Fiber",
                            DNSPrimary = "8.8.8.8",
                            DNSSecondary = "8.8.4.4",
                            DataAccountNumber = "ATT-987123456",
                            DefaultGateway = "203.0.113.1",
                            IPAddress = "203.0.113.75",
                            InternetProvider = "AT&T Business",
                            LocationId = 4,
                            MonthlyCost = 449.99m,
                            Notes = "Critical - 24/7 operations",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceType = "Fiber",
                            SubnetMask = "255.255.255.0"
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AreaManager")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("Email");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Hours")
                        .HasColumnType("text");

                    b.Property<string>("LocName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocNum")
                        .HasColumnType("integer");

                    b.Property<int>("LoctypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("RecordAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("StoreManager")
                        .HasColumnType("text");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("LocNum")
                        .IsUnique();

                    b.HasIndex("LoctypeId");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "123 Main Street",
                            AreaManager = "John Smith",
                            City = "Bossier City",
                            Email = "hq@company.com",
                            FaxNumber = "318-555-0101",
                            Hours = "Mon-Fri 8AM-5PM",
                            LocName = "Corporate Headquarters",
                            LocNum = 101,
                            LoctypeId = 1,
                            PhoneNumber = "318-555-0100",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = "LA",
                            StoreManager = "Jane Doe",
                            Zipcode = "71111"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "456 Commerce Ave",
                            AreaManager = "Mike Johnson",
                            City = "Shreveport",
                            Email = "downtown@metalmart.com",
                            FaxNumber = "318-555-0201",
                            Hours = "Mon-Sat 7AM-6PM",
                            LocName = "Downtown Metal Mart",
                            LocNum = 201,
                            LoctypeId = 2,
                            PhoneNumber = "318-555-0200",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = "LA",
                            StoreManager = "Sarah Williams",
                            Zipcode = "71101"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Address = "789 Industrial Blvd",
                            AreaManager = "Robert Brown",
                            City = "Monroe",
                            Email = "north@service.com",
                            FaxNumber = "318-555-0301",
                            Hours = "Mon-Fri 7AM-5PM",
                            LocName = "North Service Center",
                            LocNum = 601,
                            LoctypeId = 3,
                            PhoneNumber = "318-555-0300",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = "LA",
                            StoreManager = "Emily Davis",
                            Zipcode = "71201"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Address = "321 Manufacturing Dr",
                            AreaManager = "David Miller",
                            City = "Alexandria",
                            Email = "plant@company.com",
                            Hours = "24/7",
                            LocName = "Alexandria Plant",
                            LocNum = 111,
                            LoctypeId = 4,
                            PhoneNumber = "318-555-0400",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = "LA",
                            StoreManager = "Lisa Wilson",
                            Zipcode = "71301"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Address = "555 Storage Lane",
                            AreaManager = "Tom Anderson",
                            City = "Bossier City",
                            Email = "warehouse@company.com",
                            Hours = "Mon-Fri 6AM-4PM",
                            LocName = "Warehouse Storage",
                            LocNum = 901,
                            LoctypeId = 5,
                            PhoneNumber = "318-555-0500",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = "LA",
                            Zipcode = "71112"
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Loctype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoctypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Loctypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoctypeName = "Corporate"
                        },
                        new
                        {
                            Id = 2,
                            LoctypeName = "Metal Mart"
                        },
                        new
                        {
                            Id = 3,
                            LoctypeName = "Service Center"
                        },
                        new
                        {
                            Id = 4,
                            LoctypeName = "Plant"
                        },
                        new
                        {
                            Id = 5,
                            LoctypeName = "Other"
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.PhoneAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountAddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BillEntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LocalAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LocalProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("LongDistanceAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LongDistanceProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RolloverNumbers")
                        .HasColumnType("text");

                    b.Property<string>("TermNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TollFreeNumber1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TollFreeNumber2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("LocalProvider");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("PhoneAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountAddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            BillEntryDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FaxNumber = "318-555-0101",
                            LocalAccountNumber = "ATT-LOCAL-789456",
                            LocalProvider = "AT&T",
                            LocationId = 1,
                            LongDistanceAccountNumber = "ATT-LD-789456",
                            LongDistanceProvider = "AT&T",
                            MonthlyCost = 350.00m,
                            Notes = "Main phone system with 12 lines",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolloverNumbers = "318-555-0102, 318-555-0103, 318-555-0104",
                            TermNumber = "318-555-0100",
                            TollFreeNumber1 = "800-555-0100",
                            TollFreeNumber2 = "888-555-0100"
                        },
                        new
                        {
                            Id = 2,
                            AccountAddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            BillEntryDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FaxNumber = "318-555-0201",
                            LocalAccountNumber = "CTL-456789123",
                            LocalProvider = "CenturyLink",
                            LocationId = 2,
                            LongDistanceAccountNumber = "CTL-456789123",
                            LongDistanceProvider = "CenturyLink",
                            MonthlyCost = 225.00m,
                            Notes = "6 line business system",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TermNumber = "318-555-0200",
                            TollFreeNumber1 = "800-555-0200"
                        },
                        new
                        {
                            Id = 3,
                            AccountAddedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Active = true,
                            BillEntryDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FaxNumber = "318-555-0301",
                            LocalAccountNumber = "ATT-LOCAL-321654",
                            LocalProvider = "AT&T",
                            LocationId = 3,
                            LongDistanceProvider = "",
                            MonthlyCost = 175.00m,
                            Notes = "4 line system",
                            RecordAdd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TermNumber = "318-555-0300"
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.RepairContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int?>("InternetAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("PhoneAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("RPCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RPEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RPName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RPPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RPPortal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountType");

                    b.HasIndex("InternetAccountId");

                    b.HasIndex("PhoneAccountId");

                    b.ToTable("RepairContacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_RepairContact_ValidAccountType", "(\"AccountType\" = 2 AND \"PhoneAccountId\" IS NOT NULL AND \"InternetAccountId\" IS NULL) OR \r\n                     (\"AccountType\" = 1 AND \"InternetAccountId\" IS NOT NULL AND \"PhoneAccountId\" IS NULL) OR \r\n                     (\"AccountType\" = 3 AND \"InternetAccountId\" IS NOT NULL AND \"PhoneAccountId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 1,
                            InternetAccountId = 1,
                            RPCompany = "AT&T Business Repair",
                            RPEmail = "test@mcelroymetal.com",
                            RPName = "Technical Support Team",
                            RPPhone = "800-321-2000",
                            RPPortal = "https://support.business.att.com"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 1,
                            InternetAccountId = 2,
                            RPCompany = "Comcast Business Care",
                            RPEmail = "test@mcelroymetal.com",
                            RPName = "Network Operations",
                            RPPhone = "800-391-3000",
                            RPPortal = "https://business.comcast.com/support"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = 2,
                            PhoneAccountId = 1,
                            RPCompany = "AT&T Business Voice Support",
                            RPEmail = "test@mcelroymetal.com",
                            RPName = "Voice Technical Team",
                            RPPhone = "800-321-2001"
                        },
                        new
                        {
                            Id = 4,
                            AccountType = 2,
                            PhoneAccountId = 2,
                            RPCompany = "CenturyLink Repair",
                            RPEmail = "test@mcelroymetal.com",
                            RPName = "Business Support Center",
                            RPPhone = "877-453-1235",
                            RPPortal = "https://business.centurylink.com/help"
                        },
                        new
                        {
                            Id = 5,
                            AccountType = 3,
                            InternetAccountId = 3,
                            PhoneAccountId = 3,
                            RPCompany = "Suddenlink Business Support",
                            RPEmail = "test@mcelroymetal.com",
                            RPName = "Unified Support Team",
                            RPPhone = "877-694-9474",
                            RPPortal = "https://business.suddenlink.com/support"
                        });
                });

            modelBuilder.Entity("AccountInfo.Data.Models.AccountManager", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.InternetAccount", "InternetAccount")
                        .WithMany("AccountManagers")
                        .HasForeignKey("InternetAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountInfo.Data.Models.PhoneAccount", "PhoneAccount")
                        .WithMany("AccountManagers")
                        .HasForeignKey("PhoneAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InternetAccount");

                    b.Navigation("PhoneAccount");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.InternetAccount", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.Location", "Location")
                        .WithMany("InternetAccounts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Location", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.Loctype", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LoctypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.PhoneAccount", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.Location", "Location")
                        .WithOne("PhoneAccount")
                        .HasForeignKey("AccountInfo.Data.Models.PhoneAccount", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.RepairContact", b =>
                {
                    b.HasOne("AccountInfo.Data.Models.InternetAccount", "InternetAccount")
                        .WithMany("RepairContacts")
                        .HasForeignKey("InternetAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccountInfo.Data.Models.PhoneAccount", "PhoneAccount")
                        .WithMany("RepairContacts")
                        .HasForeignKey("PhoneAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InternetAccount");

                    b.Navigation("PhoneAccount");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.InternetAccount", b =>
                {
                    b.Navigation("AccountManagers");

                    b.Navigation("RepairContacts");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Location", b =>
                {
                    b.Navigation("InternetAccounts");

                    b.Navigation("PhoneAccount");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.Loctype", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("AccountInfo.Data.Models.PhoneAccount", b =>
                {
                    b.Navigation("AccountManagers");

                    b.Navigation("RepairContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
